export default {
  index: 'Provider Catalog',
  homebrew: 'Homebrew',
  apt: 'apt',
  pnpm: 'pnpm',
  npm: 'npm',
  uv: 'uv (Python)',
  goinstall: 'go install',
  cargo: 'cargo',
  'code-ext': 'VS Code Extensions',
  mas: 'Mac App Store',
  'git-config': 'git config',
  'git-clone': 'git clone',
  defaults: 'macOS defaults',
  duti: 'duti',
  bash: 'bash',
  ansible: 'Ansible',
}
