export default {
  index: 'Provider Catalog',
  homebrew: 'Homebrew',
  apt: 'apt',
  pnpm: 'pnpm',
  npm: 'npm',
  uv: 'uv (Python)',
  goinstall: 'go install',
  cargo: 'cargo',
  code: 'VS Code (`hams code`)',
  mas: 'Mac App Store',
  git: 'git (config + clone)',
  defaults: 'macOS defaults',
  duti: 'duti',
  bash: 'bash',
  ansible: 'Ansible',
}
